stages:
  - test

backend:
  stage: test
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
  script:
    - python -m pytest -q

frontend:
  stage: test
  image: node:20-alpine
  cache:
    key: frontend
    paths:
      - frontend/node_modules
  before_script:
    - cd frontend
    - npm ci
    - npm install --no-save @rollup/rollup-linux-x64-gnu || true
  script:
    - npm run build
