services:
  backend:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # Override this at build time if your backend is elsewhere
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
    ports: ["8080:80"]

