services:
  backend:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    volumes: ["./backend:/app"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health').read()"]
      interval: 10s
      timeout: 3s
      retries: 5
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    volumes: ["./frontend:/usr/src/app", "/usr/src/app/node_modules"]
    environment:
      - VITE_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --host"
